name: CI/CD

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: chrisdickinson/setup-yq@latest
      - uses: imranismail/setup-kustomize@v1
      - run: |
          yq --version
          kustomize --version
